# Generated by Django 3.1.2 on 2020-10-30 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201030_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 13, 25, 48, 884389, tzinfo=utc), verbose_name='date end'),
        ),
    ]
